# Generated by Django 5.0.6 on 2024-06-08 20:17

import django.db.models.deletion
import home.models.trip_file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('agency_name', models.TextField(blank=True, null=True)),
                ('agency_url', models.TextField(blank=True, null=True)),
                ('agency_timezone', models.TextField(blank=True, null=True)),
                ('agency_lang', models.TextField(blank=True, null=True)),
                ('agency_phone', models.TextField(blank=True, null=True)),
                ('agency_fare_url', models.TextField(blank=True, null=True)),
                ('agency_email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('monday', models.BigIntegerField(blank=True, null=True)),
                ('tuesday', models.BigIntegerField(blank=True, null=True)),
                ('wednesday', models.BigIntegerField(blank=True, null=True)),
                ('thursday', models.BigIntegerField(blank=True, null=True)),
                ('friday', models.BigIntegerField(blank=True, null=True)),
                ('saturday', models.BigIntegerField(blank=True, null=True)),
                ('sunday', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.BigIntegerField(blank=True, null=True)),
                ('end_date', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('service_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('date', models.BigIntegerField(blank=True, null=True)),
                ('exception_type', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.TextField(blank=True, null=True)),
                ('feed_publisher_url', models.TextField(blank=True, null=True)),
                ('feed_lang', models.TextField(blank=True, null=True)),
                ('feed_start_date', models.BigIntegerField(blank=True, null=True)),
                ('feed_end_date', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('second_title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('shape_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.BigIntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('stop_code', models.FloatField(blank=True, null=True)),
                ('stop_name', models.TextField(blank=True, null=True)),
                ('stop_desc', models.FloatField(blank=True, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
                ('stop_url', models.FloatField(blank=True, null=True)),
                ('location_type', models.FloatField(blank=True, null=True)),
                ('parent_station', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.IntegerField(blank=True, null=True)),
                ('to_stop_id', models.IntegerField(blank=True, null=True)),
                ('transfer_type', models.BigIntegerField(blank=True, null=True)),
                ('min_transfer_time', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/', validators=[home.models.trip_file.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('route_short_name', models.TextField(blank=True, null=True)),
                ('route_long_name', models.TextField(blank=True, null=True)),
                ('route_desc', models.FloatField(blank=True, null=True)),
                ('route_type', models.BigIntegerField(blank=True, null=True)),
                ('route_url', models.FloatField(blank=True, null=True)),
                ('route_color', models.TextField(blank=True, null=True)),
                ('route_text_color', models.TextField(blank=True, null=True)),
                ('agency_id', models.ForeignKey(blank=True, db_column='agency_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('trip_id', models.BigIntegerField(blank=True, null=True)),
                ('trip_headsign', models.FloatField(blank=True, null=True)),
                ('trip_short_name', models.FloatField(blank=True, null=True)),
                ('direction_id', models.BigIntegerField(blank=True, null=True)),
                ('block_id', models.BigIntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.FloatField(blank=True, null=True)),
                ('route_id', models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.routes')),
                ('shape_id', models.ForeignKey(blank=True, db_column='shape_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.shapes')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TextField(blank=True, null=True)),
                ('departure_time', models.TextField(blank=True, null=True)),
                ('stop_sequence', models.BigIntegerField(blank=True, null=True)),
                ('stop_headsign', models.FloatField(blank=True, null=True)),
                ('pickup_type', models.FloatField(blank=True, null=True)),
                ('drop_off_type', models.FloatField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
                ('stop_id', models.ForeignKey(blank=True, db_column='stop_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.stops')),
                ('trip_id', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.trips')),
            ],
        ),
    ]
