# Generated by Django 5.0.6 on 2024-06-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='created',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='created',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='calendardates',
            name='created',
        ),
        migrations.RemoveField(
            model_name='calendardates',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='feedinfo',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='shapes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shapes',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='stoptimes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stoptimes',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tripfile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tripfile',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='updated',
        ),
    ]
