# Generated by Django 5.0.6 on 2024-06-08 12:39

import home.models.trip_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tripfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripfile',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[home.models.trip_file.validate_file_extension]),
        ),
    ]
