# Generated by Django 5.0.6 on 2024-06-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tripfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.TextField(blank=True, null=True)),
                ('agency_name', models.TextField(blank=True, null=True)),
                ('agency_url', models.TextField(blank=True, null=True)),
                ('agency_timezone', models.TextField(blank=True, null=True)),
                ('agency_lang', models.TextField(blank=True, null=True)),
                ('agency_phone', models.TextField(blank=True, null=True)),
                ('agency_fare_url', models.TextField(blank=True, null=True)),
                ('agency_email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('monday', models.BigIntegerField(blank=True, null=True)),
                ('tuesday', models.BigIntegerField(blank=True, null=True)),
                ('wednesday', models.BigIntegerField(blank=True, null=True)),
                ('thursday', models.BigIntegerField(blank=True, null=True)),
                ('friday', models.BigIntegerField(blank=True, null=True)),
                ('saturday', models.BigIntegerField(blank=True, null=True)),
                ('sunday', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.BigIntegerField(blank=True, null=True)),
                ('end_date', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('date', models.BigIntegerField(blank=True, null=True)),
                ('exception_type', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_publisher_name', models.TextField(blank=True, null=True)),
                ('feed_publisher_url', models.TextField(blank=True, null=True)),
                ('feed_lang', models.TextField(blank=True, null=True)),
                ('feed_start_date', models.BigIntegerField(blank=True, null=True)),
                ('feed_end_date', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feed_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.BigIntegerField(blank=True, null=True)),
                ('agency_id', models.FloatField(blank=True, null=True)),
                ('route_short_name', models.TextField(blank=True, null=True)),
                ('route_long_name', models.TextField(blank=True, null=True)),
                ('route_desc', models.FloatField(blank=True, null=True)),
                ('route_type', models.BigIntegerField(blank=True, null=True)),
                ('route_url', models.FloatField(blank=True, null=True)),
                ('route_color', models.TextField(blank=True, null=True)),
                ('route_text_color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.BigIntegerField(blank=True, null=True)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.BigIntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.BigIntegerField(blank=True, null=True)),
                ('stop_code', models.FloatField(blank=True, null=True)),
                ('stop_name', models.TextField(blank=True, null=True)),
                ('stop_desc', models.FloatField(blank=True, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
                ('stop_url', models.FloatField(blank=True, null=True)),
                ('location_type', models.FloatField(blank=True, null=True)),
                ('parent_station', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.BigIntegerField(blank=True, null=True)),
                ('arrival_time', models.TextField(blank=True, null=True)),
                ('departure_time', models.TextField(blank=True, null=True)),
                ('stop_id', models.BigIntegerField(blank=True, null=True)),
                ('stop_sequence', models.BigIntegerField(blank=True, null=True)),
                ('stop_headsign', models.FloatField(blank=True, null=True)),
                ('pickup_type', models.FloatField(blank=True, null=True)),
                ('drop_off_type', models.FloatField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.BigIntegerField(blank=True, null=True)),
                ('to_stop_id', models.BigIntegerField(blank=True, null=True)),
                ('transfer_type', models.BigIntegerField(blank=True, null=True)),
                ('min_transfer_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.BigIntegerField(blank=True, null=True)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('trip_id', models.BigIntegerField(blank=True, null=True)),
                ('trip_headsign', models.FloatField(blank=True, null=True)),
                ('trip_short_name', models.FloatField(blank=True, null=True)),
                ('direction_id', models.BigIntegerField(blank=True, null=True)),
                ('block_id', models.BigIntegerField(blank=True, null=True)),
                ('shape_id', models.BigIntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
